import { NextResponse } from 'next/server';
import { generateObject } from 'ai';
import { anthropic } from '@ai-sdk/anthropic';
import prisma from '../../../../lib/prisma';
import { seoExecutionSchema } from '../../../../lib/agents/schemas';

export const maxDuration = 60; // SEO Generation can take a while

export async function POST(req) {
    try {
        const { taskId } = await req.json();

        if (!taskId) {
            return NextResponse.json({ error: 'Missing taskId' }, { status: 400 });
        }

        // 1. Fetch the exact task and its rich context
        const task = await prisma.agentTask.findUnique({
            where: { id: taskId },
            include: {
                business: {
                    include: {
                        audits: { orderBy: { created_at: 'desc' }, take: 1 },
                        competitors: true
                    }
                }
            }
        });

        if (!task || task.status !== 'QUEUED') {
            return NextResponse.json({ error: 'Task not found or not in QUEUED state.' }, { status: 400 });
        }

        // 2. Lock the task state
        await prisma.agentTask.update({
            where: { id: taskId },
            data: { status: 'PROCESSING' }
        });

        const biz = task.business;
        const auditData = biz.audits[0]?.raw_data || {};

        // 3. Construct the hardened execution system prompt
        const systemPrompt = `You are the Seleste Principal SEO Execution Agent.
You operate on a strict bounds protocol. Your job is NOT to chat or give advice. Your job is to EXECUTE specific SEO deliverables that are ready to be published.
You are tasked with: ${task.execution_type || 'SEO_OPTIMIZATION'}
Specifically: ${task.action_description}

BUSINESS CONTEXT:
Name: ${biz.name}
Industry: ${biz.industry}
Location: ${biz.location || 'Not specified'}

TARGET AUDIENCE: ${biz.target_audience || 'Not specified'}
SERVICES: ${(biz.services || []).join(', ')}

Your output must be deterministic, highly optimized for search engine visibility, and structurally perfect. Do not hallucinate facts about the business that are not provided.
If generating meta tags, keep titles < 60 chars and descriptions < 160 chars.
If drafting Schema, ensure it is 100% valid JSON-LD.
`;

        // 4. Force Claude to map its response into our exact V1 SEO Schema
        const { object: executionResult } = await generateObject({
            model: anthropic('claude-3-5-sonnet-20240620'),
            system: systemPrompt,
            prompt: `Execute the following task and return the structured JSON payload: ${task.action_description} \n\nInput Context: ${JSON.stringify(task.input_payload || {})}`,
            schema: seoExecutionSchema,
        });

        // 5. Code-level Validation Layer
        let finalStatus = 'AWAITING_APPROVAL';
        let validationReason = 'Passed automated checks.';

        if (executionResult.confidence_score < 7.0) {
            finalStatus = 'VALIDATION_FAILED';
            validationReason = 'Low confidence score generated by LLM logic step.';
        }

        // 6. Save the Output Payload and transition the State Machine
        const updatedTask = await prisma.agentTask.update({
            where: { id: taskId },
            data: {
                status: finalStatus,
                execution_type: executionResult.execution_type,
                output_payload: {
                    summary: executionResult.summary,
                    rationale: executionResult.rationale,
                    draft: executionResult.draft_output
                },
                confidence_score: executionResult.confidence_score,
                validation_status: validationReason
            }
        });

        return NextResponse.json({
            success: true,
            status: finalStatus,
            data: updatedTask
        });

    } catch (error) {
        console.error('SEO Agent Execution Error:', error);

        // Fail Gracefully in DB if possible
        try {
            const body = await req.json();
            if (body.taskId) {
                await prisma.agentTask.update({
                    where: { id: body.taskId },
                    data: {
                        status: 'VALIDATION_FAILED',
                        validation_status: `Runtime Error: ${error.message}`
                    }
                });
            }
        } catch (e) { }

        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
