import React from 'react'
import { MarketingLayout } from '../components/MarketingLayout'

export default function Terms() {
  return (
    <MarketingLayout>
      <div style={{ backgroundColor: 'var(--bg)', padding: '6rem 2rem' }}>
        <div style={{ maxWidth: 800, margin: '0 auto' }}>
          <header style={{ textAlign: 'center', marginBottom: '5rem' }}>
            <h1 style={{ fontFamily: 'var(--ff-display)', fontSize: '3.5rem', fontWeight: 800, marginBottom: '1.5rem', color: 'var(--text)' }}>
              Terms of Service.
            </h1>
            <p style={{ fontSize: '1.25rem', color: 'var(--text2)', lineHeight: 1.6 }}>
              The standards governing our intelligence platform and audit engine.
            </p>
          </header>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '3rem', color: 'var(--text2)', lineHeight: 1.8, fontSize: 15 }}>
            <section>
              <h3 style={{ color: 'var(--text)', marginBottom: '1rem' }}>1. Usage Limitations</h3>
              <p>You agree to use our intelligence engine only for authorized business URLs that you own or have permission to analyze. Automated scraping of our reports or using our data to build competing auditing services is strictly prohibited.</p>
            </section>

            <section>
              <h3 style={{ color: 'var(--text)', marginBottom: '1rem' }}>2. Intelligence Reports</h3>
              <p>All scores, findings, and growth roadmaps generated by Seleste are provided for informational purposes only. While our extraction engine is highly accurate, we do not guarantee specific business outcomes as a result of implementing our recommendations.</p>
            </section>

            <section>
              <h3 style={{ color: 'var(--text)', marginBottom: '1rem' }}>3. Subscription & Billings</h3>
              <p>Pro plans are billed on a recurring monthly basis. You can manage and cancel your subscriptions from your dashboard. Refunds are governed by our Satisfaction Policy (available in our FAQ).</p>
            </section>

            <section>
              <h3 style={{ color: 'var(--text)', marginBottom: '1rem' }}>4. Analysis Ownership</h3>
              <p>By running an audit, you grant Seleste a non-exclusive license to use the extracted data points for anonymized industry standards and model improvements. Your specific business result remains your asset for internal use.</p>
            </section>
          </div>
        </div>
      </div>
    </MarketingLayout>
  )
}
