// Use the Prisma client generated by the backend (shared schema)
// On Render, 'npm run build' runs prisma generate before tsc
import { PrismaClient } from '../../backend/node_modules/@prisma/client'
import { PrismaPg } from '../../backend/node_modules/@prisma/adapter-pg'
import { Pool } from 'pg'
import dotenv from 'dotenv'
dotenv.config({ path: '../backend/.env' })

const dbUrl = process.env.DATABASE_URL
if (!dbUrl) throw new Error('DATABASE_URL is not set')

const pool = new Pool({ connectionString: dbUrl })
const adapter = new PrismaPg(pool as any)

export const db = new PrismaClient({ adapter } as any)
